version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    container_name: db
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"